import { useAppStore } from '@/store/useAppStore'
import { Button } from '@/components/ui/button'
import { IntInput, MoneyInput, PercentInput, SliderField, TextInput } from '@/components/fields/NumberField'
import { formatMoney, formatPercent } from '@/lib/format'
import { makeId } from '@/engine/ids'
import { fundAnnualContributionAt } from '@/engine/fund'
import type { AnalysisResult } from '@/engine/types'

const selectCls = 'flex h-9 w-full rounded-md border border-input bg-transparent px-2 text-sm shadow-xs focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring'

export function CurrentFundsEditor() {
  const cash = useAppStore((s) => s.cash); const pools = useAppStore((s) => s.pools); const fund = useAppStore((s) => s.fund); const global = useAppStore((s) => s.global)
  const updateCash = useAppStore((s) => s.updateCash); const updateFund = useAppStore((s) => s.updateFund); const setFund = useAppStore((s) => s.setFundAccount)
  const investTotal = pools.reduce((sum, pool) => sum + pool.initialBalance, 0)
  const enableFund = () => setFund({ initialBalance: 50_000, contributionSegments: [{ id: makeId(), startYear: global.startYear, endYear: global.startYear + 19, annualAmount: 48_000 }], interestRate: 0.015, maturityPolicy: 'withdrawToWealth', maturityPrepayEffect: 'shorten-term', withdrawToPoolId: pools[0]?.id })
  return <div className="space-y-4">
    <p className="rounded-md bg-muted/60 px-2 py-1.5 text-[11px] leading-relaxed text-muted-foreground">这里填<b className="text-foreground">现在已经有的钱</b>。工资和每年公积金缴存请在「收入」填写；理财的收益和风险在「投资情况」配置。</p>
    <div className="grid grid-cols-3 gap-2 rounded-lg border bg-muted/25 p-2 text-center text-[11px]"><AssetTotal label="活钱" value={cash.initialBalance} /><AssetTotal label="理财本金" value={investTotal} /><AssetTotal label="公积金余额" value={fund?.initialBalance ?? 0} /></div>
    <section className="space-y-2"><span className="text-sm font-medium">活钱（活期）</span><div className="grid grid-cols-2 gap-2"><Field label="当前余额"><MoneyInput value={cash.initialBalance} onChange={(v) => updateCash({ initialBalance: v })} /></Field><Field label="初始全部转入"><select value={cash.sweepToPoolId ?? ''} onChange={(e) => updateCash({ sweepToPoolId: e.target.value || undefined })} className={selectCls}><option value="">留在活钱</option>{pools.map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}</select></Field></div></section>
    <section className="space-y-2 border-t pt-3"><div className="flex items-center justify-between"><span className="text-sm font-medium">公积金账户</span><label className="flex items-center gap-1.5 text-xs text-muted-foreground"><input type="checkbox" checked={fund !== null} onChange={(e) => e.target.checked ? enableFund() : setFund(null)} className="accent-primary" />启用</label></div>
      {fund ? <><div className="grid grid-cols-2 gap-2"><Field label="当前余额（锁定资金）"><MoneyInput value={fund.initialBalance} onChange={(v) => updateFund({ initialBalance: v })} /></Field><Field label="账户计息利率"><PercentInput value={fund.interestRate} onChange={(v) => updateFund({ interestRate: v })} /></Field></div><FundMaturitySettings /></> : <p className="text-xs text-muted-foreground">启用后可在「收入」填写每年缴存额，并在「贷款情况」里设置月冲。</p>}
    </section>
  </div>
}

export function InvestmentEditor() {
  const pools = useAppStore((s) => s.pools); const global = useAppStore((s) => s.global); const setGlobal = useAppStore((s) => s.setGlobal); const addPool = useAppStore((s) => s.addPool); const updatePool = useAppStore((s) => s.updatePool); const removePool = useAppStore((s) => s.removePool)
  return <div className="space-y-2"><div className="rounded-lg border border-dashed p-3"><Field label="活钱兜底池年化"><PercentInput value={global.cashExpectedAnnualReturn ?? 0.01} onChange={(v) => setGlobal({ cashExpectedAnnualReturn: v })} /></Field><p className="mt-1 text-[11px] leading-relaxed text-muted-foreground">所有活钱（包括应急 reserve）按这个年化逐月计息，随时可用于生活费、月供和提前还款；默认 1%，不参与压力回撤。</p></div><p className="text-xs text-muted-foreground">其他理财池代表不同投资方式；本金是你现在已经投进去的钱。</p>{pools.map((pool) => <div key={pool.id} className="rounded-lg border p-3 space-y-2"><div className="flex items-center gap-2"><TextInput value={pool.name} onChange={(v) => updatePool(pool.id, { name: v })} className="h-8 flex-1" /><Button variant="ghost" size="sm" className="h-7 px-2" onClick={() => removePool(pool.id)}>✕</Button></div><div className="grid grid-cols-3 gap-2"><Field label="当前本金"><MoneyInput value={pool.initialBalance} onChange={(v) => updatePool(pool.id, { initialBalance: v })} /></Field><Field label="预期年化"><PercentInput value={pool.expectedAnnualReturn} onChange={(v) => updatePool(pool.id, { expectedAnnualReturn: v })} /></Field><Field label="最大亏损"><PercentInput value={pool.maxLossPct} onChange={(v) => updatePool(pool.id, { maxLossPct: v })} /></Field></div><Field label="风险档"><select value={pool.riskLevel} onChange={(e) => updatePool(pool.id, { riskLevel: e.target.value as 'high' | 'medium' | 'low' })} className={selectCls}><option value="high">高风险</option><option value="medium">中风险</option><option value="low">低风险</option></select></Field><SliderField label="预期年化（拖动实时看结论变化）" value={pool.expectedAnnualReturn} min={0} max={0.12} step={0.002} onChange={(v) => updatePool(pool.id, { expectedAnnualReturn: v })} format={(v) => formatPercent(v, 1)} /></div>)}<div className="flex gap-2"><Button variant="outline" size="sm" onClick={() => addPool('high')}>+ 高风险</Button><Button variant="outline" size="sm" onClick={() => addPool('medium')}>+ 中风险</Button><Button variant="outline" size="sm" onClick={() => addPool('low')}>+ 低风险</Button></div></div>
}

export function FundIncomeEditor() {
  const fund = useAppStore((s) => s.fund); const global = useAppStore((s) => s.global); const add = useAppStore((s) => s.addFundContributionSegment); const update = useAppStore((s) => s.updateFundContributionSegment); const remove = useAppStore((s) => s.removeFundContributionSegment)
  if (!fund) return <p className="rounded-md bg-muted/60 px-2 py-1.5 text-xs text-muted-foreground">未启用公积金账户。请先在「当前资金账户」启用并填写当前余额。</p>
  const endYear = Math.max(...(fund.contributionSegments ?? []).map((item) => item.endYear)); const effectiveEnd = global.retireYear == null ? endYear : Math.min(endYear, global.retireYear)
  return <div className="space-y-1.5"><div className="flex items-center justify-between"><span className="text-sm font-medium">公积金年度缴存（个人+单位合计）</span><Button variant="outline" size="sm" className="h-7" onClick={add}>+ 新增阶段</Button></div><p className="rounded-md bg-muted/60 px-2 py-1.5 text-[11px] leading-relaxed text-muted-foreground">填写每年<b className="text-foreground">新缴进公积金账户</b>的钱；可按涨薪、换工作、退休前后分段调整。</p><div className="grid grid-cols-[1fr_1fr_1.4fr_auto] gap-1.5 px-0.5 text-[10px] text-muted-foreground"><span>起始年</span><span>结束年</span><span>每年缴存额</span><span /></div>{(fund.contributionSegments ?? []).map((segment) => <div key={segment.id} className="grid grid-cols-[1fr_1fr_1.4fr_auto] gap-1.5"><IntInput value={segment.startYear} min={1990} max={2120} onChange={(v) => update(segment.id, { startYear: v })} /><IntInput value={segment.endYear} min={1990} max={2120} onChange={(v) => update(segment.id, { endYear: v })} /><MoneyInput value={segment.annualAmount} onChange={(v) => update(segment.id, { annualAmount: v })} /><Button variant="ghost" size="sm" className="h-8 px-2" onClick={() => remove(segment.id)}>✕</Button></div>)}<p className="text-[11px] text-muted-foreground">未覆盖年份视为不再缴存；当前最晚缴存到 {effectiveEnd} 年。</p></div>
}

export function MortgagePaymentStrategy({ result }: { result: AnalysisResult }) {
  const global = useAppStore((s) => s.global); const fund = useAppStore((s) => s.fund); const loans = useAppStore((s) => s.loans); const setGlobal = useAppStore((s) => s.setGlobal); const enabled = global.fundMonthlyOffset !== false
  const snap = result.outcomes[result.baselineId]?.base.snaps[0]; const contribution = fund ? fundAnnualContributionAt(fund, global.startYear) / 12 : 0; const due = snap?.loans.filter((item) => loans.find((loan) => loan.id === item.loanId)?.kind !== 'other').reduce((sum, item) => sum + item.scheduledPayment, 0) ?? 0; const gap = Math.max(0, due - contribution); const buffer = gap > 0 && fund ? Math.floor(fund.initialBalance / gap) : Infinity
  return <section className="space-y-2 border-t pt-3"><span className="block text-sm font-medium">房贷月供资金策略</span>{!fund ? <p className="text-xs text-muted-foreground">未启用公积金账户，房贷月供将从活钱或设置的理财补足。</p> : <>{enabled && due > 0 && <div className={`rounded-md border p-2 text-[11px] leading-relaxed ${gap > 0 ? 'border-status-severe/30 bg-status-severe/8' : 'border-status-good/30 bg-status-good/8'}`}><b className="text-foreground">公积金月冲缓冲判断</b><p className="mt-0.5 text-muted-foreground">每月缴存约 {formatMoney(contribution)}，当前房贷月供约 {formatMoney(due)}。{gap > 0 ? <>每月差约 <b className="text-status-severe">{formatMoney(gap)}</b>，当前余额约能补 {buffer} 个月；年底全部年冲后会更早改由活钱承担。</> : <>每月可多出约 <b className="text-status-good">{formatMoney(contribution - due)}</b>，通常可积累为年底年冲余额。</>}</p></div>}<label className="flex cursor-pointer items-start gap-2 rounded-md border p-2 text-xs hover:bg-accent/50"><input type="radio" name="fund-offset-strategy" checked={enabled} onChange={() => setGlobal({ fundMonthlyOffset: true })} className="mt-0.5 accent-primary" /><span><b>优先公积金月冲</b>——房贷先扣公积金，不够的活钱补。</span></label><label className="flex cursor-pointer items-start gap-2 rounded-md border p-2 text-xs hover:bg-accent/50"><input type="radio" name="fund-offset-strategy" checked={!enabled} onChange={() => setGlobal({ fundMonthlyOffset: false })} className="mt-0.5 accent-primary" /><span><b>全部用活钱付</b>——公积金只攒着计息，仅供对比。</span></label></>}</section>
}

function FundMaturitySettings() { const fund = useAppStore((s) => s.fund)!; const pools = useAppStore((s) => s.pools); const global = useAppStore((s) => s.global); const update = useAppStore((s) => s.updateFund); const label = global.retireYear ? `退休可取后怎么处理（${global.retireYear} 年）` : '停止缴存/退休可取后怎么处理'; return <div className="space-y-2"><Field label={label}><select value={fund.maturityPolicy} onChange={(e) => update({ maturityPolicy: e.target.value as never })} className={selectCls}><option value="hold">留在公积金账户继续计息</option><option value="withdrawToWealth">一次性取出，转入理财池</option><option value="lumpPrepay">一次性冲抵贷款</option></select></Field>{fund.maturityPolicy === 'lumpPrepay' && <Field label="冲抵效果"><select value={fund.maturityPrepayEffect} onChange={(e) => update({ maturityPrepayEffect: e.target.value as never })} className={selectCls}><option value="shorten-term">缩短期限</option><option value="reduce-payment">减少月供</option></select></Field>}{fund.maturityPolicy === 'withdrawToWealth' && <Field label="转入理财池"><select value={fund.withdrawToPoolId ?? ''} onChange={(e) => update({ withdrawToPoolId: e.target.value || undefined })} className={selectCls}>{pools.map((pool) => <option key={pool.id} value={pool.id}>{pool.name}</option>)}</select></Field>}</div> }
function AssetTotal({ label, value }: { label: string; value: number }) { return <div><p className="text-muted-foreground">{label}</p><p className="font-mono font-medium">{formatMoney(value)}</p></div> }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block space-y-1"><span className="block text-xs text-muted-foreground">{label}</span>{children}</label> }
